# accessed via {{ site.myvariable }}

title: Code standard by truesnow
email: chrisx0909@gmail.com
description: >-
  Code standard summary during work. Such as MySQL standard,
  tech scheme standard, error code standard, service app id standard, etc.
baseurl: ""
url:
# twitter_username: jekyllrb
github_username:  truesnow

include:
  - _redirects

# Build settings
# theme: minima
remote_theme: ronv/colorie
plugins_dir: _plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - disqus-for-jekyll

permalink: pretty

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug
  tags:
    output: true
    permalink: /tag/:tag

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

  - scope:
      path: "assets/images"
    values:
      image: true
